export const ERROR_CONST = {
  PRICE_OUT_OF_BAND: 'FO0001',
  ORDER_TYPE_NOT_SUPPORTED: 'FO0002',
  INVALID_QUANTITY_LOT: 'FO0003',
  INVALID_PRICE: 'FO0004',
  STOCK_NOT_FOUND: 'FO0005',
  INSUFFICIENT_BALANCE: 'FO0006',
  INSUFFICIENT_SELLABLE_QTY: 'FO0007',
  ORDER_NOT_CANCELLABLE: 'FO0008',
  MISSING_REFERENCE_PRICE: 'FO0009',
  TRADING_ACCOUNT_NOT_FOUND: 'FO0010',
  WALLET_NOT_FOUND: 'FO0011',
  CURRENT_PASSWORD_INVALID: 'FO0012',
  AUTH_INVALID_CREDENTIALS: 'FO0013',
  AUTH_REFRESH_TOKEN_MISSING: 'FO0014',
  AUTH_REFRESH_TOKEN_INVALID: 'FO0015',
  AUTH_CUSTID_CONFLICT: 'FO0016',
  AUTH_REGISTER_FAILED: 'FO0017',
  AUTH_INVALID_TOKEN: 'FO0018',
} as const;

export type AppErrorKey = keyof typeof ERROR_CONST;
export type AppErrorCode = (typeof ERROR_CONST)[AppErrorKey];
